flagList = [
    [
        "../src/img/svg/square/raimbow.svg",
        "../src/img/svg/square/homo.svg",
        "../src/img/svg/square/lesbian.svg",
        "../src/img/svg/square/bisexual.svg",
        "../src/img/svg/square/pansexual.svg",
        "../src/img/svg/square/asexual.svg",
        "../src/img/svg/square/transgender.svg",
        "../src/img/svg/square/demiboy.svg",
        "../src/img/svg/square/demigirl.svg",
        "../src/img/svg/square/nonbinary.svg"
    ],[
        "../src/img/svg/circle/raimbow.svg",
        "../src/img/svg/circle/homo.svg",
        "../src/img/svg/circle/lesbian.svg",
        "../src/img/svg/circle/bisexual.svg",
        "../src/img/svg/circle/pansexual.svg",
        "../src/img/svg/circle/asexual.svg",
        "../src/img/svg/circle/transgender.svg",
        "../src/img/svg/circle/demiboy.svg",
        "../src/img/svg/circle/demigirl.svg",
        "../src/img/svg/circle/nonbinary.svg"
    ]
]